name: cuda build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  cuda-build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        cuda: [ '12.1.0', '12.2.0', '12.3.0', '12.4.0', '12.5.0', '12.6.0' ]
        # all available versions:
        # https://github.com/Jimver/cuda-toolkit/blob/master/src/links/linux-links.ts

    name: cuda build ${{ matrix.cuda }} - ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    steps:
    - uses: jimver/cuda-toolkit@v0.2.19
      id: cuda-toolkit
      with:
        cuda: ${{ matrix.cuda }}
        method: 'network'
        sub-packages: '[ "nvcc" ]'

    - name: check NVCC
      run: nvcc -V

    - name: install dependencies
      run:
        sudo apt install -y cmake libglu1-mesa-dev libpng-dev libx11-dev xorg-dev

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: build
      run:
        mkdir build;
        cd build;
        cmake ..;
        make -j2;
        # `make -j` could crash CI instances because of limited memory
