name: cuda build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  schedule:
    - cron: "0 0 1 * *"
    # runs on 00:00 1st day of every month
    # 00:00 UTC = 08:00 Beijing
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  cuda-build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ] # namely ubuntu 24.04
        cuda: [ '12.6.0', '12.8.0' ]
        # you need at least 12.6.0 to build cuda::std::variant
        # available versions:
        # https://github.com/Jimver/cuda-toolkit/blob/master/src/links/linux-links.ts
        float_config: [" -DPBRT_FLOAT_AS_DOUBLE=off", " -DPBRT_FLOAT_AS_DOUBLE=on"]

    name: cuda ${{ matrix.cuda }} ${{ matrix.float_config }} - ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    steps:
    - uses: jimver/cuda-toolkit@v0.2.23
      id: cuda-toolkit
      with:
        cuda: ${{ matrix.cuda }}
        method: 'network'
        sub-packages: '[ "nvcc" ]'

    - name: check NVCC
      run: nvcc -V

    - name: install dependencies
      run:
        sudo apt install -y cmake libglfw3-dev libglu1-mesa-dev libpng-dev libx11-dev xorg-dev libxrandr-dev

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: build
      run:
        mkdir build;
        cd build;
        cmake .. ${{ matrix.float_config }};
        make -j2;
        # `make -j` could crash CI instances because of limited memory
